FROM registry.redhat.io/ubi10/php-83:latest
LABEL description="WordPress Final on UBI 10"

USER 0

# 1. Installera felsökningsverktyg (MariaDB-client & Netcat)
RUN dnf -y install mariadb nc && \
    dnf clean all

# 2. Ladda ner och packa upp WordPress
RUN curl -L https://wordpress.org/latest.tar.gz -o /tmp/wordpress.tar.gz && \
    tar -xzf /tmp/wordpress.tar.gz -C /opt/app-root/src --strip-components=1 && \
    rm /tmp/wordpress.tar.gz

# 3. Kopiera config
COPY wp-config.php /opt/app-root/src/wp-config.php

# 4. Rättigheter
RUN chown -R 1001:0 /opt/app-root/src && \
    chmod -R g+w /opt/app-root/src

USER 1001

CMD /usr/libexec/s2i/run