FROM registry.redhat.io/ubi10/ubi:latest
LABEL description="MariaDB on UBI 10 - Custom Build"

# 1. Konfigurera MariaDB Repo (eftersom det kan saknas i UBI 10 base)
COPY mariadb.repo /etc/yum.repos.d/

RUN dnf install -y mariadb-server

RUN mkdir -p /var/lib/mariadb \
    && chown -R mysql:mysql /var/lib/mariadb \
    && mkdir -p /var/run/mysqld \
    && chown -R mysql:mysql /var/run/mysqld

EXPOSE 3306

CMD ["/usr/sbin/mariadbd"]
