FROM registry.redhat.io/ubi10/ubi:latest
LABEL description="MariaDB on UBI 10 - Custom Build"

# 1. Konfigurera MariaDB Repo (eftersom det kan saknas i UBI 10 base)
COPY mariadb.repo /etc/yum.repos.d/

# 2. Installera MariaDB Server
RUN dnf -y install MariaDB-server MariaDB-client findutils procps-ng && \
    dnf clean all

RUN mkdir -p /var/lib/mariadb && mkdir -p /var/run/mysqld

RUN mariadb-install-db --user=mysql ata=/var/lib/mariadb

EXPOSE 3306

CMD ["/usr/sbin/mariadbd"]
