apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: ghcr.io/svartastorken/ubi10-mariadb-12.2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_USER
              value: "wordpress"
            - name: MARIADB_PASSWORD
              value: "hemligt"      # I produktion bör detta vara en Secret
            - name: MARIADB_DATABASE
              value: "wordpress_db"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"