apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: ghcr.io/svartastorken/ubi10-mariadb-12.2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: db-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: db-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: db-name
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"