name: Bulding and Deploying WordPress with MariaDB

on:
  push:
    branches:
      - test-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubi10-mariadb-12.2
  OPENSHIFT_NAMESPACE: test-miljo2

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to redhat registry
        uses: redhat-actions/podman-login@v1.7
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_USERNAME }}
          password: ${{ secrets.RH_PASSWORD }}
      
      - name: set up buildah
        uses: redhat-actions/buildah-build@v2.13
        with: 
          image: ${{ env.IMAGE_NAME }}
          context: ./mariadb
          tags: |
            latest
            v2.0
          containerfiles: ./mariadb/Containerfile

      - name: Push MariaDB image to GitHub Packages Registry
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            v2.0
          registry: ${{ env.REGISTRY }}/svartastorken
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: ocp install
        uses: redhat-actions/oc-installer@v1.2

      - name: Login to OpenShift cluster
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER}}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Deploy MariaDB to OpenShift
        run: |
          oc apply -f ./mariadb/mariadb-deployment.yaml
          oc rollout restart deployment/mariadb

